server:
  servlet:
    context-path: /NoteStack
spring:
  messages: { encoding: UTF-8, basename: messages }
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:h2:mem:TestDB
    driver-class-name: org.h2.Driver
    username: admin //Just used for testing
    password: admin //Just used for testing

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/
